<?php

namespace Database\Seeders;

use App\Models\KManeKachuwa;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class KManeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        KManeKachuwa::insert(
            [

                [
                    'byanjan_id' => '1',
                    'kmk_name' => 'कछुवा',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '1',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '2',
                    'kmk_name' => 'खरायो',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '2',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '3',
                    'kmk_name' => 'गमला',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '3',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '4',
                    'kmk_name' => 'घडी',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '4',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '5',
                    'kmk_name' => 'ङ',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '5',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '6',
                    'kmk_name' => 'चरा',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '6',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '7',
                    'kmk_name' => 'छाता',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '7',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '8',
                    'kmk_name' => 'जरायो',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '8',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '9',
                    'kmk_name' => 'झान्डा',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '9',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '10',
                    'kmk_name' => 'गोरुसिङे ञ',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '10',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '11',
                    'kmk_name' => 'टपरी',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '11',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '12',
                    'kmk_name' => 'ठेकी',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '12',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '13',
                    'kmk_name' => 'डमरु',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '13',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '14',
                    'kmk_name' => 'ढकनी',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '14',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '15',
                    'kmk_name' => 'वाण',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '15',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '16',
                    'kmk_name' => 'तराजू',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '16',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '17',
                    'kmk_name' => 'थरमस',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '17',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '18',
                    'kmk_name' => 'दमकल',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '18',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '19',
                    'kmk_name' => 'धरहरा',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '19',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '20',
                    'kmk_name' => 'नङ',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '20',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '21',
                    'kmk_name' => 'परेवा',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '21',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '22',
                    'kmk_name' => 'फलफुल',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '22',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '23',
                    'kmk_name' => 'बस',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '23',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '24',
                    'kmk_name' => 'भकुन्डो',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '24',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '25',
                    'kmk_name' => 'मकै',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '25',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '26',
                    'kmk_name' => 'यज्ञ',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '26',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '27',
                    'kmk_name' => 'रथ',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '27',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '28',
                    'kmk_name' => 'लसुन',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '28',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '29',
                    'kmk_name' => 'वकिल',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '29',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '30',
                    'kmk_name' => 'शन्ख',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '30',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '31',
                    'kmk_name' => 'षत्कोण',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '31',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '32',
                    'kmk_name' => 'सलाई',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '32',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '33',
                    'kmk_name' => 'हलो',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '33',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '34',
                    'kmk_name' => 'क्षत्रीय',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '34',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '35',
                    'kmk_name' => 'त्रसुल',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '35',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'byanjan_id' => '36',
                    'kmk_name' => 'ज्ञानी',
                    'kmk_image' => '464548453354.png',
                    'kmk_audio' => '464548453354.m4a',
                    'kmk_order' => '36',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ]
            ]
        );
    }
}
