<?php

namespace Database\Seeders;

use App\Models\Sankhya;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class SankhyaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Sankhya::insert(
            [

                [
                    'sankhya_name' => '०',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '1',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '१',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '2',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '२',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '3',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '३',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '4',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '४',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '5',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '५',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '6',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '६',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '7',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '७',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '8',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '८',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '9',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '९',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '10',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '१०',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '11',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '११',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '12',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '१२',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '13',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '१३',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '14',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '१४',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '15',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '१५',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '16',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '१६',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '17',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '१७',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '18',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '१८ ',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '19',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '१९',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '20',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '२०',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '21',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '२१',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '22',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '२२',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '23',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '२३',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '24',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '२४',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '25',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '२५',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '26',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '२६',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '27',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '२७',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '28',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '२८',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '29',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '२९',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '30',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '३०',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '31',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '३१',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '32',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '३२',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '33',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '३३',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '34',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '३४',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '35',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '३५',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '36',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '३६',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '37',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '३७',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '38',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '३८',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '39',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '३९',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '40',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '४०',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '41',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '४१',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '42',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '४२',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '43',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '४३',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '44',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '४४',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '45',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '४५',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '46',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '४६',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '47',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '४७',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '48',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '४८',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '49',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '४९',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '50',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '५०',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '51',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '५१ ',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '52',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '५२',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '53',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '५३',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '54',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '५४',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '55',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '५५',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '56',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '५६',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '57',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '५७',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '58',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '५८',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '59',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '५९',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '60',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '६०',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '61',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '६१',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '62',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '६२',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '63',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '६३',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '64',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '६४',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '65',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '६५ ',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '66',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '६६',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '67',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '६७',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '68',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '६८',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '69',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '६९',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '70',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '७०',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '71',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '७१',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '72',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '७२',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '73',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '७३',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '74',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '७४',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '75',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '७५',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '76',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '७६',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '77',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '७७',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '78',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '७८',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '79',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '७९',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '80',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '८०',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '81',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '८१',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '82',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '८२',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '83',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '८३',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '84',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '८४',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '85',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '८५',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '86',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '८६',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '87',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '८७',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '88',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '८८',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '89',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '८९',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '90',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '९०',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '91',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '९१',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '92',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '९२',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '93',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '९३',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '94',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '९४',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '95',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '९५',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '96',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '९६',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '97',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '९७',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '98',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '९८',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '99',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '९९',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '100',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'sankhya_name' => '१००',
                    'sankhya_audio' => '74471622379739.mp3',
                    'sankhya_order' => '101',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ]
            ]
        );
    }
}
